version: "3.9"

services:
  accesslog:
    image: diamol/ch04-access-log
    networks:
      - zad10-2tbk

  iotd:
    image: diamol/ch04-image-of-the-day
    ports:
      - "8088:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/image"]
      interval: 5s
      timeout: 20s
      retries: 2
      start_period: 10s
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        order: start-first
        monitor: 90s
        failure_action: rollback
      rollback_config:
        parallelism: 4
        order: start-first
        failure_action: continue
    networks:
      - zad10-2tbk

  image-gallery:
    image: diamol/ch04-image-gallery
    ports:
      - "80:80"
    networks:
      - zad10-2tbk

networks:
  zad10-2tbk:
    name: zad10-2tbk